# Generated by Django 4.0.7 on 2023-01-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Emailid', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('ConfirmPassword', models.CharField(max_length=20)),
                ('Phoneno', models.CharField(max_length=10)),
                ('Companyname', models.CharField(max_length=40)),
                ('County', models.CharField(max_length=40)),
                ('pincode', models.CharField(max_length=20)),
                ('Domain', models.CharField(choices=[('LESSOR', 'lessor'), ('LESSEE', 'lessee')], max_length=20)),
            ],
        ),
    ]
