# Generated by Django 4.0.7 on 2023-01-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_containerupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='leasingcontainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
                ('Count', models.IntegerField(default=0)),
                ('Price', models.CharField(max_length=20)),
                ('Leaseddate', models.CharField(max_length=20)),
                ('Returndate', models.CharField(max_length=20)),
                ('Lessename', models.CharField(max_length=20)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
